### ISSUE TITLE
Kullanıma Al Butonu

### ISSUE THREAD

**Issue by burakkarabakla** [cagatayozata/AnimalCherish#55]
Her bir cinsi tek tek kullanıma almak zorundayız ve örneğin sayfa beş(5)teki bir cinsi kullanıma aldıktan sonra yeniden ilk sayfaya yönlendiriliyoruz. Bu düzeltilmeli.

**Comment by muammersahin** [comment]
Güvenlik amacıyla genel kurallara uymamız gerekmekte. Bu fonksiyonellik sistemde yavaşlığa ve kullanım zorluğuna yol açabilir.
