### ISSUE TITLE
Timeout problemi

### ISSUE THREAD

**Issue by burakkarabakla** [cagatayozata/AnimalCherish#62]
Kullanıcı bir süre işlem yapmadığında sistemden otomatik çıkış yapılmasına rağmen buna ilişkin bir uyarı mesajı yok. Kullanıcı sonradan bir işlem yapmaya çalıştığında sadece o işlem yapılamıyor.

**Comment by muammersahin** [comment]
Spring genel güvenlik kuralıdır
